spring:
  profiles.active: prod
  data:
    mongodb:
      database: ${MONGODB_DB:tickets}
      port: ${MONGODB_PORT:27017}
      host: ${MONGODB_HOST:localhost}
  security:
    user:
      name: ticket
      password: ticket

management:
  server:
    port: 8082
    endpoint:
      health:
        show-details: always

ticket:
  fine:
    speeding: 80
    parking: 40


